name: datingacademy
favicon: null
layout_spectrum: 0.03109581721946597
typography_spectrum: 0.12245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9838876647409052
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
